version: 2.1

executors:
  machine_executor_amd64:
    machine:
      image: ubuntu-2204:2022.04.2
    environment:
      architecture: "amd64"
      platform: "linux/amd64"

orbs:
  terraform: circleci/terraform@3.2.1

jobs:
  deploy-ocp:
    executor: machine_executor_amd64
    steps:
      - checkout
      - run:
          name: Login OpenShift
          command: |
            wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
            tar -xvf openshift-client-linux.tar.gz
            ./oc login -u admin -p ${ADMIN_PASSWORD} --server=${CLUSTER_API_URL} --insecure-skip-tls-verify=true
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: 0.14.2
      - terraform/init:
          path: servicemesh/
      - terraform/validate:
          path: servicemesh/
      - terraform/plan:
          path: servicemesh/
          var: domain=${CLUSTER_API_URL},cluster-context=${CLUSTER_CONTEXT}

workflows:
  terratest:
    jobs:
      - deploy-ocp:
          context: OpenShift