projects:
  - name: acm
    namespace: openshift-gitops
applications:
  - name: local-cluster-config
    namespace: openshift-gitops
    project: default
    source:
      repoURL: https://github.com/piomin/openshift-cluster-config.git
      targetRevision: HEAD
      path: clusters
      helm:
        valueFiles:
          - values-local.yaml
    destination:
      server: https://kubernetes.default.svc
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  - name: cicd-config
    namespace: openshift-gitops
    project: default
    source:
      repoURL: https://github.com/piomin/openshift-cluster-config.git
      targetRevision: HEAD
      path: cicd
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
  - name: multi-cluster-config
    namespace: openshift-gitops
    project: default
    source:
      repoURL: https://github.com/piomin/openshift-cluster-config.git
      targetRevision: HEAD
      path: multicluster
    destination:
      server: https://kubernetes.default.svc
applicationsets:
  - name: cluster-config
    namespace: openshift-gitops
    generators:
      - clusterDecisionResource:
          configMapRef: acm-placement
          labelSelector:
            matchLabels:
              cluster.open-cluster-management.io/placement: demo-global
          requeueAfterSeconds: 180
    template:
      metadata:
        name: '{{name}}-cluster-config'
      spec:
        destination:
          server: '{{server}}'
        project: default
        source:
          path: clusters
          repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
          targetRevision: master
          helm:
            valueFiles:
              - values-remote.yaml
        syncPolicy:
          automated:
            selfHeal: true